import { NewsArticleDTO } from '../../types/dto/fakenews.dto';

export const FAKE_NEWS_DATABASE: NewsArticleDTO[] = [
  // ==========================================
  // JUNIOR (Klasse 4–5): Skurrile Fakes & echte Tier-/Naturwunder
  // ==========================================
  {
    id: 'jun-fake-1',
    headline: 'Sensation im Tierpark: Erstes Elefanten-Zebra der Welt geboren!',
    teaserText: 'Im Stadtzoo staunten die Tierpfleger nicht schlecht: Ein Tierbaby mit Rüssel und schwarz-weißen Zebrastreifen kam zur Welt. Besucher stehen stundenlang Schlange.',
    sourceName: 'tierfreunde-viral-news.biz',
    sourceUrl: 'http://tierfreunde-viral-news.biz/elefanten-zebra',
    category: 'Tiere & Natur',
    publishDate: 'Gestern, 14:30 Uhr',
    isFake: true,
    difficulty: 'JUNIOR',
    redFlags: [
      {
        clue: 'Biologische Unmöglichkeit',
        explanation: 'Elefanten und Zebras sind genetisch völlig verschieden und können biologisch keine gemeinsamen Tierkinder zeugen.',
        toolType: 'PLAUSIBILITY_CHECK',
      },
      {
        clue: 'Dubiose Internetadresse (.biz)',
        explanation: 'Echte Tierparks und Zoos veröffentlichen Geburten auf offiziellen Websites oder in anerkannten Zeitungen, nicht auf Werbe-Blogs mit der Endung .biz.',
        toolType: 'SOURCE_CHECK',
      },
    ],
    factCheckTips: 'Wenn ein Zootier wie ein Fabelwesen aussieht, handelt es sich fast immer um ein KI-generiertes Bild oder eine Photoshop-Montage.',
    realBackground: 'Tatsächlich wurde im Zoo kürzlich ein ganz normales Steppenzebra-Fohlen geboren – ein Besucher erstellte daraus zum Spaß ein KI-Bild.',
  },
  {
    id: 'jun-real-1',
    headline: 'NASA-Sonde fliegt so nah an die Sonne wie nie zuvor',
    teaserText: 'Die Raumsonde "Parker Solar Probe" ist mit über 600.000 km/h durch die äußere Atmosphäre der Sonne geflogen. Ein Spezial-Hitzeschild schützt die Bordinstrumente.',
    sourceName: 'ZDF logo! Kindernachrichten',
    sourceUrl: 'https://www.zdf.de/kinder/logo',
    category: 'Wissenschaft & Raumfahrt',
    publishDate: 'Heute, 09:15 Uhr',
    isFake: false,
    difficulty: 'JUNIOR',
    redFlags: [],
    factCheckTips: 'Seriöse Wissenschafts-Meldungen nennen konkrete Missionen und werden von öffentlich-rechtlichen Kinder-Nachrichten bestätigt.',
    realBackground: 'Die Parker Solar Probe der NASA erforscht seit mehreren Jahren die Sonnenwinde.',
  },
  {
    id: 'jun-fake-2',
    headline: 'Zahnärzte empfehlen: Schokolade essen schützt vor Karies!',
    teaserText: 'Eine geheime Studie will herausgefunden haben, dass Vollmilchschokolade die Zähne härter macht als jede Zahnpasta. Kinder sollen dreimal täglich naschen.',
    sourceName: 'schoko-paradies-fun.de',
    sourceUrl: 'http://schoko-paradies-fun.de/gesunde-zaehne',
    category: 'Gesundheit & Ernährung',
    publishDate: 'Vor 2 Tagen',
    isFake: true,
    difficulty: 'JUNIOR',
    redFlags: [
      {
        clue: 'Widerspruch zum gesunden Menschenverstand',
        explanation: 'Zucker ist die Hauptnahrung für Kariesbakterien im Mund. Kein echter Zahnarzt empfiehlt Schokolade zum Zähneputzen.',
        toolType: 'PLAUSIBILITY_CHECK',
      },
      {
        clue: 'Angebliche "geheime Studie"',
        explanation: 'Wissenschaftliche Studien werden in Fachmagazinen veröffentlicht. Das Wort "geheim" ist ein typischer Trick von Fake News.',
        toolType: 'LANGUAGE_CHECK',
      },
    ],
    factCheckTips: 'Frage bei Gesundheitsthemen immer Erwachsene oder Ärzt:innen, statt Blogbeiträgen von Süßwaren-Herstellern zu glauben.',
  },
  {
    id: 'jun-real-2',
    headline: 'Verblüffende Vogel-Schläue: Krähen können zählen und Gesichter merken!',
    teaserText: 'Forscher der Universität Tübingen haben nachgewiesen, dass Rabenkrähen die Anzahl von Tönen mitzählen und sich Gesichter von Menschen über Jahre einprägen können.',
    sourceName: 'GEOlino Forschung',
    sourceUrl: 'https://www.geolino.de/tiere',
    category: 'Tiere & Natur',
    publishDate: 'Vor 3 Tagen',
    isFake: false,
    difficulty: 'JUNIOR',
    redFlags: [],
    factCheckTips: 'Echte Tiermeldungen stützen sich auf renommierte Universitäten und anerkannte Verhaltensbiologen.',
  },
  {
    id: 'jun-fake-3',
    headline: 'Fliegende Pinguine am Nordpol gesichtet!',
    teaserText: 'Forscher trauten ihren Augen kaum: Ganze Schwärme von Pinguinen sollen fliegend über das Eismeer gezogen sein. Experten sprechen von einer weltweiten Sensation.',
    sourceName: 'tier-wunder-aktuell.net',
    sourceUrl: 'http://tier-wunder-aktuell.net/flying-penguins',
    category: 'Tiere & Natur',
    publishDate: 'Gestern, 18:00 Uhr',
    isFake: true,
    difficulty: 'JUNIOR',
    redFlags: [
      {
        clue: 'Falscher Lebensraum & Anatomie',
        explanation: 'Pinguine leben auf der Südhalbkugel (Antarktis), nicht am Nordpol! Zudem sind ihre Flügel zu Flossen fürs Tauchen umgebildet und können sie nicht in die Luft tragen.',
        toolType: 'PLAUSIBILITY_CHECK',
      },
      {
        clue: 'Keine konkreten Forscher benannt',
        explanation: 'Es heißt nur ungenau "Forscher trauten ihren Augen kaum" – keine Universität oder Institutsname wird erwähnt.',
        toolType: 'SOURCE_CHECK',
      },
    ],
    factCheckTips: 'Der Aprilscherz mit fliegenden Pinguinen stammt ursprünglich von der britischen BBC aus dem Jahr 2008!',
  },
  {
    id: 'jun-real-3',
    headline: 'Klimaschutz an Schulen: Schüler pflanzen Mini-Wälder auf dem Schulhof',
    teaserText: 'Mit sogenannten "Tiny Forests" kühlen Grundschüler ihre Schulumgebung ab. Über 300 einheimische Bäume wurden in Berlin gemeinsam mit Förstern eingepflanzt.',
    sourceName: 'Tagesschau in einfacher Sprache',
    sourceUrl: 'https://www.tagesschau.de/in-einfacher-sprache',
    category: 'Umwelt & Schule',
    publishDate: 'Heute, 11:20 Uhr',
    isFake: false,
    difficulty: 'JUNIOR',
    redFlags: [],
    factCheckTips: 'Konkrete Schulprojekte mit Beteiligung lokaler Förster sind überprüfbar und plausibel.',
  },

  // ==========================================
  // SENIOR (Ab Klasse 6): Subtile Desinformation, Clickbait & Dramatisierung
  // ==========================================
  {
    id: 'sen-fake-1',
    headline: 'EILMELDUNG: Bundesweites Handy-Verbot ab 18 Uhr für Jugendliche beschlossen!',
    teaserText: 'Wegen Schlafmangels soll das Ministerium ein neues Gesetz verabschiedet haben: Ab Montag müssen Provider das Mobilfunknetz für Unter-16-Jährige nachts kappen.',
    sourceName: 'aktuell-express-news24.de',
    sourceUrl: 'http://aktuell-express-news24.de/handy-aus',
    category: 'Politik & Alltag',
    publishDate: 'Heute, 07:45 Uhr',
    isFake: true,
    difficulty: 'SENIOR',
    redFlags: [
      {
        clue: 'Panikmache durch "EILMELDUNG" in Großbuchstaben',
        explanation: 'Falschmeldungen erzeugen künstliche Dringlichkeit, damit Menschen den Beitrag sofort weiterleiten, bevor sie nachdenken.',
        toolType: 'LANGUAGE_CHECK',
      },
      {
        clue: 'Fehlende Berichterstattung in Leitmedien',
        explanation: 'Ein solches Bundesgesetz wäre das Top-Thema in allen seriösen Nachrichtensendungen (Tagesschau, heute-journal). Dort findet sich keine Zeile darüber.',
        toolType: 'SOURCE_CHECK',
      },
      {
        clue: 'Rechtliche & technische Unmöglichkeit',
        explanation: 'Mobilfunk-Provider können das Alter der Endnutzer gar nicht individuell am Sendemast für einzelne Rufnummern zeitgesteuert drosseln.',
        toolType: 'PLAUSIBILITY_CHECK',
      },
    ],
    factCheckTips: 'Wenn eine Schlagzeile starke Wut oder Angst auslöst, atme durch und suche auf seriösen Nachrichtenseiten nach der Meldung.',
    realBackground: 'Einige Schulen diskutieren freiwillige Smartphone-Regeln im Unterricht – von einem nächtlichen staatlichen Netz-Ausfall war nie die Rede.',
  },
  {
    id: 'sen-real-1',
    headline: 'EU-Gesetz in Kraft: Einheitliches USB-C-Ladekabel für alle Smartphones',
    teaserText: 'Kabel-Chaos ade: Hersteller müssen neue Handys, Tablets und Kameras mit dem gleichen USB-C-Anschluss ausstatten. Das spart tonnenweise Elektroschrott.',
    sourceName: 'heise online / c\'t Magazin',
    sourceUrl: 'https://www.heise.de',
    category: 'Technik & Umwelt',
    publishDate: 'Vor 4 Tagen',
    isFake: false,
    difficulty: 'SENIOR',
    redFlags: [],
    factCheckTips: 'Echte Technik-Gesetze werden von Fachmagazinen wie Heise oder Golem detailliert mit Stichtagen und Übergangsfristen beschrieben.',
  },
  {
    id: 'sen-fake-2',
    headline: 'Gefahr beim Gaming: Neuer Virus in Roblox stiehlt unbemerkt Ersparnisse der Eltern!',
    teaserText: 'Ein geheimer Trojaner namens "RoboDrain" soll sich über Chat-Nachrichten verbreiten und direkt auf Bankkonten zugreifen. Experten fordern sofortige Kontolöschung.',
    sourceName: 'gaming-alert-insider.net',
    sourceUrl: 'http://gaming-alert-insider.net/roblox-danger',
    category: 'Gaming & Sicherheit',
    publishDate: 'Vor 1 Tag',
    isFake: true,
    difficulty: 'SENIOR',
    redFlags: [
      {
        clue: 'Reißerische Dramatisierung ohne technische Details',
        explanation: 'Chat-Nachrichten können ohne das Anklicken schädlicher Links oder Downloads keine automatischen Banküberweisungen auf dem PC ausführen.',
        toolType: 'PLAUSIBILITY_CHECK',
      },
      {
        clue: 'Anonyme "Experten" ohne Namen',
        explanation: 'Wenn Artikel von "Experten fordern..." schreiben, ohne ein echtes Sicherheitsunternehmen (z. B. BSI, Kaspersky) zu nennen, ist Skepsis geboten.',
        toolType: 'LANGUAGE_CHECK',
      },
    ],
    factCheckTips: 'Prüfe bei Gaming-Warnungen offizielle Sicherheitswarnungen des Bundesamts für Sicherheit in der Informationstechnik (BSI).',
  },
  {
    id: 'sen-real-2',
    headline: 'Meeresbiologie: Forscher entschlüsseln Lautsprache von Pottwalen mit KI',
    teaserText: 'Mit maschinellem Lernen analysierten Meeresforscher tausende Klick-Muster von Walen. Sie entdeckten komplexe Lautfolgen, ähnlich einem Alphabet.',
    sourceName: 'National Geographic Deutschland',
    sourceUrl: 'https://www.nationalgeographic.de',
    category: 'Wissenschaft & KI',
    publishDate: 'Gestern, 16:10 Uhr',
    isFake: false,
    difficulty: 'SENIOR',
    redFlags: [],
    factCheckTips: 'Wissenschaftliche Durchbrüche werden mit Forschungspartnern (hier: Project CETI) und wissenschaftlichen Veröffentlichungen belegt.',
  },
  {
    id: 'sen-fake-3',
    headline: 'Skandal-Leak: Beliebte Video-App speichert heimlich Gedanken von Schülern!',
    teaserText: 'Laut einem Whistleblower nutzen die Frontkameras von Handys Mikrobewegungen der Augen, um heimlich die Schulfächer und Noten der Nutzer auszulesen.',
    sourceName: 'tech-truth-leaks.org',
    sourceUrl: 'http://tech-truth-leaks.org/eye-leak',
    category: 'Technik & Datenschutz',
    publishDate: 'Vor 2 Tagen',
    isFake: true,
    difficulty: 'SENIOR',
    redFlags: [
      {
        clue: 'Völlig absurde technische Behauptung ("Gedankenlesen")',
        explanation: 'Keine Handykamera der Welt kann Gedanken oder Schulnoten durch Augenbewegungen auslesen.',
        toolType: 'PLAUSIBILITY_CHECK',
      },
      {
        clue: 'Verschwörungstheorie-Vokabular ("Skandal-Leak", "Whistleblower")',
        explanation: 'Falschmeldungen nutzen oft Begriffe aus Spionage-Thrillern, um glaubwürdig und geheimnisvoll zu wirken.',
        toolType: 'LANGUAGE_CHECK',
      },
    ],
    factCheckTips: 'Datenschutz-Bedenken bei Social-Media sind real, aber Technologien zum "Gedankenlesen" per Handykamera existieren nicht.',
  },
  {
    id: 'sen-real-3',
    headline: 'Klima-Erkenntnis: Wolken enthalten winzige Mikroplastik-Partikel',
    teaserText: 'Japanische Umweltforscher haben auf Berggipfeln Wassertropfen aus Wolken analysiert und mikroskopisch kleine Plastikteilchen nachgewiesen.',
    sourceName: 'Spiegel Wissenschaft',
    sourceUrl: 'https://www.spiegel.de/wissenschaft',
    category: 'Umwelt & Forschung',
    publishDate: 'Vor 5 Tagen',
    isFake: false,
    difficulty: 'SENIOR',
    redFlags: [],
    factCheckTips: 'Veröffentlicht im Fachblatt "Environmental Chemistry Letters" und von unabhängigen Umweltinstituten bestätigt.',
  },
];
